CREATE TABLE IF NOT EXISTS mlb_game_context (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  event_id TEXT NOT NULL,
  event_market_id TEXT,
  source_key TEXT NOT NULL,
  sportsbook_key TEXT,
  sportsbook_name TEXT,
  season INTEGER NOT NULL,
  game_date TIMESTAMPTZ NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  team_competitor_id TEXT NOT NULL,
  opponent_competitor_id TEXT,
  team_name TEXT NOT NULL,
  opponent_name TEXT,
  team_abbr TEXT,
  opponent_abbr TEXT,
  is_home BOOLEAN NOT NULL,
  side TEXT NOT NULL,
  market_type TEXT NOT NULL,
  line DOUBLE PRECISION,
  opening_line DOUBLE PRECISION,
  closing_line DOUBLE PRECISION,
  odds_american INTEGER,
  opening_odds_american INTEGER,
  closing_odds_american INTEGER,
  implied_probability DOUBLE PRECISION,
  is_favorite BOOLEAN,
  is_underdog BOOLEAN,
  favorite_price_bucket TEXT,
  moneyline_bucket TEXT,
  spread_bucket TEXT,
  total_bucket TEXT,
  team_score INTEGER,
  opponent_score INTEGER,
  won_game BOOLEAN,
  cover_result TEXT,
  ou_result TEXT,
  total_runs INTEGER,
  margin INTEGER,
  venue TEXT,
  park_id TEXT,
  division_game BOOLEAN,
  is_day_game BOOLEAN,
  is_night_game BOOLEAN,
  previous_game_date TIMESTAMPTZ,
  days_rest DOUBLE PRECISION,
  opponent_days_rest DOUBLE PRECISION,
  is_back_to_back BOOLEAN,
  travel_spot TEXT,
  last_game_runs_scored INTEGER,
  last_game_runs_allowed INTEGER,
  last_two_runs_scored INTEGER,
  last_three_runs_scored INTEGER,
  starter_pitcher_id TEXT,
  starter_pitcher_name TEXT,
  starter_rolling_game_score DOUBLE PRECISION,
  team_pregame_elo DOUBLE PRECISION,
  opponent_pregame_elo DOUBLE PRECISION,
  elo_diff DOUBLE PRECISION,
  weather_temp_f DOUBLE PRECISION,
  wind_mph DOUBLE PRECISION,
  wind_direction TEXT,
  wind_out BOOLEAN,
  wind_in BOOLEAN,
  data_quality_score INTEGER NOT NULL DEFAULT 0,
  data_warnings JSONB,
  raw_context_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS mlb_game_context_unique_idx
  ON mlb_game_context (event_id, event_market_id, team_competitor_id, market_type, side);
CREATE INDEX IF NOT EXISTS mlb_game_context_season_game_date_idx ON mlb_game_context (season, game_date);
CREATE INDEX IF NOT EXISTS mlb_game_context_team_season_idx ON mlb_game_context (team_name, season);
CREATE INDEX IF NOT EXISTS mlb_game_context_market_season_idx ON mlb_game_context (market_type, season);
CREATE INDEX IF NOT EXISTS mlb_game_context_source_season_idx ON mlb_game_context (source_key, season);
CREATE INDEX IF NOT EXISTS mlb_game_context_home_market_idx ON mlb_game_context (is_home, market_type);
CREATE INDEX IF NOT EXISTS mlb_game_context_favorite_market_idx ON mlb_game_context (is_favorite, market_type);
