FROM node:20-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
COPY prisma ./prisma
RUN npm ci --include=dev || true

COPY . .

CMD ["sh", "-lc", "npm run dev -- -p ${PORT:-3000}"]
